// <auto-generated />
using System;
using AnimalShelter.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AnimalShelter.Api.Migrations
{
    [DbContext(typeof(AnimalShelterDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "adoption_state", new[] { "rejected", "inprocess", "completed", "canceled" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "animal_state", new[] { "waiting", "in_adoption", "adopted", "not_available" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "animal_type", new[] { "dog", "cat" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "user_rol", new[] { "volunteer", "adopter", "admin" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "user_state", new[] { "active", "inactive", "suspended" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AnimalShelter.Api.Models.AdoptionModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AdopterId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("AdoptionDate")
                        .HasColumnType("date");

                    b.Property<int>("AnimalId")
                        .HasColumnType("integer");

                    b.Property<int>("State")
                        .HasColumnType("adoption_state");

                    b.Property<int>("VolunteerId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AdopterId");

                    b.HasIndex("AnimalId");

                    b.HasIndex("VolunteerId");

                    b.ToTable("Adoptions");
                });

            modelBuilder.Entity("AnimalShelter.Api.Models.AnimalModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("Age")
                        .HasColumnType("integer");

                    b.Property<string>("Breed")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("State")
                        .HasColumnType("animal_state");

                    b.Property<int>("Type")
                        .HasColumnType("animal_type");

                    b.HasKey("Id");

                    b.ToTable("Animals");
                });

            modelBuilder.Entity("AnimalShelter.Api.Models.UserModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Rol")
                        .HasColumnType("user_rol");

                    b.Property<int>("State")
                        .HasColumnType("user_state");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("AnimalShelter.Api.Models.AdoptionModel", b =>
                {
                    b.HasOne("AnimalShelter.Api.Models.UserModel", "Adopter")
                        .WithMany("AdopterAdoptions")
                        .HasForeignKey("AdopterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AnimalShelter.Api.Models.AnimalModel", "Animal")
                        .WithMany("Adoptions")
                        .HasForeignKey("AnimalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AnimalShelter.Api.Models.UserModel", "Volunteer")
                        .WithMany("VolunteerAdoptions")
                        .HasForeignKey("VolunteerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Adopter");

                    b.Navigation("Animal");

                    b.Navigation("Volunteer");
                });

            modelBuilder.Entity("AnimalShelter.Api.Models.AnimalModel", b =>
                {
                    b.Navigation("Adoptions");
                });

            modelBuilder.Entity("AnimalShelter.Api.Models.UserModel", b =>
                {
                    b.Navigation("AdopterAdoptions");

                    b.Navigation("VolunteerAdoptions");
                });
#pragma warning restore 612, 618
        }
    }
}
